In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import cross_validate
from sklearn.metrics.scorer import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.svm import SVC

In [10]:
df = pd.read_csv('New_ds_final_2.csv')

In [4]:
dfdata = df.iloc[:,1:-1]

In [5]:
dftarget = df['target_loan_status']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(dfdata, dftarget, test_size=0.3)

In [17]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)
lr.predict(X_test.tail())

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([1, 1, 1, 1, 1])

In [8]:
df.head()

Unnamed: 0  Unnamed: 0.1       id  loan_amnt  funded_amnt  funded_amnt_inv  \
0           0             0  1077501       5000         5000           4975.0   
1           1             1  1077430       2500         2500           2500.0   
2           2             2  1077175       2400         2400           2400.0   
3           3             3  1076863      10000        10000          10000.0   
4           4             4  1075358       3000         3000           3000.0   

   term  int_rate  installment  home_ownership         ...          \
0     1     10.65       162.87               1         ...           
1     2     15.27        59.83               1         ...           
2     1     15.96        84.33               1         ...           
3     1     13.49       339.31               1         ...           
4     2     12.69        67.79               1         ...           

   last_pymnt_amnt  last_fico_range_high  last_fico_range_low  policy_code  \
0           171.62                   734                  730            1   
1           119.66                   499                    0            1   
2           649.91                   739                  735            1   
3           357.48                   604                  600            1   
4            67.30                   684                  680            1   

   acc_now_delinq  delinq_amnt  pub_rec_bankruptcies  group_emp_length  \
0               0            0                     0                 3   
1               0            0                     0                 0   
2               0            0                     0                 3   
3               0            0                     0                 3   
4               0            0                     0                 0   

   group_annual_inc  target_loan_status  
0                 1                   1  
1                 1                   0  
2                 0                   1  
3                 2                   1  
4                 4                   1  

[5 rows x 44 columns]

In [39]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)
rf.predict(X_test.tail())

array([1, 0, 1, 1, 1])

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
from sklearn.model_selection import KFold

In [29]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [59]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    print(model.predict(X1).astype(int))
    return model.score(X_test, y_test)

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


In [31]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [62]:
scores_l = []
scores_rf = []

for train_index, test_index in kf.split(dfdata):
    X_train, X_test, y_train, y_test = dfdata.iloc[train_index], dfdata.iloc[test_index],\
    dftarget.iloc[train_index], dftarget.iloc[test_index]
    
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[1 0 1 1 1]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[1 0 1 1 1]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[1 0 1 1 1]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[1 0 1 1 1]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[1 0 1 1 1]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[1 0 1 1 1]


In [61]:
scores_l

[0.9899967065086706, 0.993118550782448, 0.9735700460243916]

In [40]:
scores_rf

[0.998589164785553, 0.9992239858906525, 0.9966137566137566]

In [19]:
from sklearn.model_selection import cross_val_score

In [46]:
cross_val_score(MultinomialNB(), dfdata, dftarget)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.65653217, 0.73862434, 0.81968254])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=4), dfdata, dftarget)

In [ ]:
y_pred_test = lr.predict(X_test)
dfdata1 = accuracy_score(y_pred = y_pred_test, y_true = y_test)

CM = confusion_matrix(y_pred = y_pred_test, y_true = y_test)
CMatrix(CM)

In [41]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [42]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
nb = MultinomialNB()
nb.fit(X_train, y_train)
nb.score(X_test, y_test)


0.8427513227513228

In [44]:
cross_val_score(MultinomialNB(), dfdata, dftarget)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.65653217, 0.73862434, 0.81968254])

In [52]:
import xgboost as xgb

In [50]:
!pip install xgboost

     |████████████████████████████████| 142.8MB 1.9kB/s eta 0:00:013  |█▊                              | 7.8MB 4.3MB/s eta 0:00:32     |███████                         | 31.6MB 673kB/s eta 0:02:46     |████████▍                       | 37.2MB 2.2MB/s eta 0:00:48     |█████████▋                      | 43.1MB 2.1MB/s eta 0:00:47     |███████████████                 | 66.8MB 3.7MB/s eta 0:00:21     |██████████████████▋             | 83.1MB 2.6MB/s eta 0:00:24     |████████████████████▊           | 92.5MB 5.0MB/s eta 0:00:11     |█████████████████████           | 93.5MB 5.0MB/s eta 0:00:10     |█████████████████████▎          | 95.1MB 3.2MB/s eta 0:00:16     |█████████████████████▍          | 95.5MB 3.2MB/s eta 0:00:15     |█████████████████████████▋      | 114.4MB 181kB/s eta 0:02:37     |█████████████████████████▋      | 114.5MB 181kB/s eta 0:02:36     |█████████████████████████▉      | 115.4MB 181kB/s eta 0:02:31     |██████████████████████████      | 116.1MB 790kB/s eta 0:00:34     |██

In [53]:
xgb_model = xgb.XGBRegressor(objective="reg:linear", random_state=42)

In [54]:
xgb_model.fit(X_train, y_train)
xgb_model.score(X_test,y_test)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[23:28:10] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


0.9735700460243916

In [56]:
xgb_model.predict(X1).astype(int)

array([0, 0, 1, 0, 1])

In [ ]:
cross_val_score(xgb.XGBRegressor(objective="reg:linear", random_state=42), dfdata, dftarget)

In [35]:
X1 = dfdata.tail(5)

In [ ]:
dftarget.head(10)